# Generated by Django 3.0.3 on 2020-04-11 12:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=20)),
                ('s_name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
                ('occupation', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=15)),
                ('gitgub_address', models.CharField(max_length=30)),
                ('linkedin_address', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
                ('profile_pic', models.ImageField(upload_to='author_pic/')),
                ('authorise', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email_id', models.EmailField(max_length=254)),
                ('profile_pic', models.ImageField(upload_to='user_pic/')),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorID', models.IntegerField()),
                ('author_name', models.CharField(max_length=25)),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to='thumbnail_img/')),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=5000)),
                ('accessible', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.Author')),
            ],
        ),
    ]
