# Generated by Django 3.0.3 on 2020-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='authorise',
        ),
        migrations.RenameField(
            model_name='myuser',
            old_name='is_staff',
            new_name='is_author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='f_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gitgub_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='is_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='myuser',
            name='linkedin_address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='s_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
