# Generated by Django 3.0.3 on 2020-04-11 12:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 12, 40, 57, 176726, tzinfo=utc)),
        ),
    ]
