# Generated by Django 3.0.3 on 2020-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='instagram_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Framework', 'Framework'), ('Hacking', 'Hacking'), ('Language', 'Language'), ('Other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='linkedin_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
