# Generated by Django 3.0.3 on 2020-05-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='f_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='s_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
