# Generated by Django 3.0.3 on 2020-05-10 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='authorise',
        ),
    ]
