# Generated by Django 3.0.3 on 2020-04-14 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_myuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='gitgub_address',
            new_name='github_address',
        ),
    ]
