# Generated by Django 3.0.3 on 2020-04-17 10:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_test1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_msg', models.CharField(max_length=200)),
                ('U_Email_id', models.EmailField(max_length=254)),
                ('U_name', models.CharField(max_length=25)),
                ('cmt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Article')),
            ],
        ),
        migrations.DeleteModel(
            name='Test1',
        ),
    ]
