# Generated by Django 3.0.3 on 2020-04-19 14:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20200417_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercomments',
            old_name='U_msg',
            new_name='u_msg',
        ),
        migrations.RenameField(
            model_name='usercomments',
            old_name='U_name',
            new_name='u_name',
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='U_Email_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='accessible',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='authorID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author_name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='article',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='github_address',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ReplyComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_msg', models.CharField(max_length=200)),
                ('u_name', models.CharField(max_length=25)),
                ('cmt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Article')),
                ('main_cmt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.UserComments')),
            ],
        ),
    ]
