# Generated by Django 3.0.3 on 2020-04-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='authorID',
        ),
    ]
