# Generated by Django 3.0.3 on 2020-04-20 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_remove_article_authorid'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
